### PR TITLE
Issue 14

### PR DESCRIPTION
**Pull request by pythonguru101**
https://github.com/EnsembleGovServices/kamodo-core/issues/14

### CODE REVIEW

**Comment by asherp** [comment]
One of our usage notebooks is breaking with this change `docs/notebooks/Kamodo.ipynb`
```python
kamodo = Kamodo('mass[kg] = x', 'vol[m^3] = y')
kamodo['rho'] = 'mass/vol' # registers rho(y,x) (this is fine)
kamodo['rho(x,y)[g/cm^3]'] = 'mass/vol' # should have registered rho(x,y) but instead raises SyntaxError: Ordering error
```

**Comment by asher-pembroke** [comment]
Great! Can you comment your code to explain why this works? Also, please move the fix into a separate function within util.py

**Comment by asher-pembroke** [comment]
Once you've commented your code, please include the alphabetical ordering fix described here #26

**Comment by asher-pembroke** [comment]
Is this pull covered by pull #27? Should I close it without merging?

**Comment by pythonguru101** [comment]
Yes, please close this PR. cause PR #27  has both changes

**Pull request closed without merging**
