### PR TITLE
Partial fix

### LINKED ISSUE #38: partial kwargs do not render properly [bug]
## Describe the bug
the @partial decorator does not render latex well in titles:

1. All defaults are printed in the updated equation, rather than just the partial values
2. Presence of partial keys in arg_units metadata confuses the 2d plotting units

### PR DESCRIPTION
**Pull request by asher-pembroke**
Fixes #38

### CODE REVIEW

**Comment by asher-pembroke** [comment]
This fix is pretty good, but can we improve on the title a bit? It seems overly verbose.

```python
from kamodo import kamodofy, Kamodo, partial

@partial(z=5)
@kamodofy(units = 'cm^2', arg_units=dict(x_N='cm', y_N='cm', z='km'))
def f_NN(x_N = np.linspace(0, 8*np.pi, 90), y_N = np.linspace(0, 5, 90), z = 4):
    x, y = np.meshgrid(x_N, y_N, indexing = 'ij')
    return np.sin(x)*y*z

kamodo = Kamodo(f_NN = f_NN)
kamodo.plot('f_NN')
```

newplot (5)

**Comment by asher-pembroke** [comment]
This code should have produced the same plot as above, but fails

```python
@kamodofy(units = 'cm^2', arg_units=dict(x_N='cm', y_N='cm', z='km'))
def f_NN(x_N = np.linspace(0, 8*np.pi, 90), y_N = np.linspace(0, 5, 90), z = 4):
    x, y = np.meshgrid(x_N, y_N, indexing = 'ij')
    return np.sin(x)*y*z

kamodo = Kamodo(f_NN = f_NN)
kamodo.plot('f_NN', plot_partial=dict(f_NN=dict(z=3)))
```
<details>
<summary> expand for error </summary>

```console
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_14/1048537249.py in <module>
      5 
      6 kamodo = Kamodo(f_NN = f_NN)
----> 7 kamodo.plot('f_NN', plot_partial=dict(f_NN=dict(z=3)))

/kamodo-core/kamodo/kamodo.py in plot(self, plot_partial, *variables, **figures)
   1144             for k, v in plot_partial.items():
   1145                 regname = k
-> 1146                 kpartial[regname] = partial(kpartial[k], **v)
   1147             return kpartial.plot(*variables, **figures)
   1148 

/kamodo-core/kamodo/util.py in partial(_func, **partial_kwargs)
   1379         wrapped._repr_latex_ = new_latex_func
   1380         wrapped.meta = orig_meta
-> 1381         if orig_docs is not None:
   1382             wrapped.__doc__ += "\n" + f.__doc__
   1383 

/kamodo-core/kamodo/util.py in decorator_partial(f)
   1309         if orig_equation is None:
   1310             orig_equation = orig_latex_func()
-> 1311         orig_meta['equation'] = orig_equation.strip("$")
   1312 
   1313         # remove partials from arg units dictionary

AttributeError: 'NoneType' object has no attribute 'strip'
```
</detail>

**Comment by pythonguru101** [comment]
@asher-pembroke can you please tell me which branch to work for this issue? or tell me the issue no..

**Comment by asher-pembroke** [comment]
@pythonguru101 looks like the merge with master corrected the issue.

**Pull request merged**
