### PR TITLE
Arg units mixed with Dimensionless breaks unit conversion [Bug] #16

### PR DESCRIPTION
**Pull request by pythonguru101**

### CODE REVIEW

**Comment by asher-pembroke** [comment]
The `arg_units` are correct but the generated formula does not match the expected result. I've  improved the test to check for this. Also the arg_units do not match the generated latex.

**Comment by pythonguru101** [comment]
@asher-pembroke where can I find the improved test case?

**Comment by asher-pembroke** [comment]
> @asher-pembroke where can I find the improved test case?

I committed this to Issue-16 branch https://github.com/EnsembleGovServices/kamodo-core/pull/50/commits/1b0e09f1c3f5a89fa34984b32d67e6a7ec0c389c

**Comment by pythonguru101** [comment]
@asher-pembroke Need some help on this bug:
`self.unit_registry` I am getting like this:
`OrderedDict([(f(x), f(kilogram)), (f(kilogram), gram), (g(z), g(centimeter)), (g(centimeter), kilogram), (h(y), gram), (T(x, y, z), T(gram, meter, centimeter)), (T(gram, meter, centimeter), kilogram)])`

So, for this: `k.T(3.,4.,5.)` what will be the units for `x->3,y->4,z->5` here and what will be the desired `unit conversion` to get value 50?
The equation I am getting is:
`Eq(T(x, y, z), f(x/1000)/1000 + g(z) + h(y)/1000)`, should it be just `f(x)+f(y)+f(z)`?

**Comment by asher-pembroke** [comment]
> @asher-pembroke Need some help on this bug: `self.unit_registry` I am getting like this: `OrderedDict([(f(x), f(kilogram)), (f(kilogram), gram), (g(z), g(centimeter)), (g(centimeter), kilogram), (h(y), gram), (T(x, y, z), T(gram, meter, centimeter)), (T(gram, meter, centimeter), kilogram)])`

The problem is that extract_units is returning the wrong units for the left-hand-side string. That causes the wrong units to be inserted into the unit_registry. I've added test_extract_units in the latest commit to test for this.

> So, for this: `k.T(3.,4.,5.)` what will be the units for `x->3,y->4,z->5` here and what will be the desired `unit conversion` to get value 50? The equation I am getting is: `Eq(T(x, y, z), f(x/1000)/1000 + g(z) + h(y)/1000)`, should it be just `f(x)+f(y)+f(z)`?

I rechecked my math and I think you should be getting when you register `k['T(x[g], y, z[m])[kg]'] = 'f+h+g'`
```
T=f(x/1000)/1000 + h(y)/1000 + g(100*z)
```
It's the same as you have except that z gets converted to meters befor being passed to `g`. I've updated the test to reflect this correction.

**Comment by asher-pembroke** [comment]
The latex rendering for dimensionless arguments needs to be replaced with just the argument instead of y[Dimension(1)]. Here's what it looks like now:

```python
@kamodofy(units='g', arg_units=dict(x='kg'))
def f(x):
    return x**2


@kamodofy(units='g')
def h(y):
    return y**2

@kamodofy(units='kg', arg_units=dict(z='cm'))
def g(z):
    return z**2


k = Kamodo(f=f, g=g, h=h)

k['T(x[g], y, z[m])[kg]'] = 'f+h+g'
k.T
```

𝑇(𝑥[𝑔],𝑦[𝐷𝑖𝑚𝑒𝑛𝑠𝑖𝑜𝑛(1)],𝑧[𝑚])[𝑘𝑔]=𝑓(𝑥1000)1000+𝑔(100𝑧)+ℎ(𝑦)1000

**Comment by pythonguru101** [comment]
@asher-pembroke 
Already solved and pushed earlier in issue-16 branch

**Pull request merged**
